---
abstract: 'NativeTrait-like behavior for Moo.'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  MooX::Types::MooseLike::Base: '0.23'
  Test::Exception: '0'
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-HandlesVia
requires:
  Class::Method::Modifiers: '0'
  Data::Perl: '0.002006'
  Module::Runtime: '0'
  Moo: '1.003000'
  Role::Tiny: '0'
resources:
  repository: git://github.com/tobyink/MooX-HandlesVia.git
version: '0.001009'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
